### ISSUE TITLE
lldb in MaterialButton

### ISSUE THREAD

**Issue by cohix** [GraphKit/MaterialKit#47]
Bug in MaterialButton in this block:
```
private func prepareBackgroundColorView() {
		backgroundColorView.translatesAutoresizingMaskIntoConstraints = false
		backgroundColorView.layer.masksToBounds = true
		backgroundColorView.clipsToBounds = true
		backgroundColorView.userInteractionEnabled = false
		insertSubview(backgroundColorView, atIndex: 0)
		Layout.expandToParent(self, child: backgroundColorView)
	}
```
Where the insertSubview line fails with lldb

**Comment by cohix** [comment]
I may have resolved by just adding self. to the offending line. Will keep testing.

Issue was intermittent to start, stack trace gave me little to no info.

**Comment by danieldahan** [comment]
Okay, are you testing 1.12, or dev?

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by cohix** [comment]
I'm actually using the issue-44 branch that no longer exists because it was 
the
only one that would compile on Xcode 7. Tell me which branch to test and 
I'll do
so.

**Comment by danieldahan** [comment]
I merged issue-44 into dev. That should work fine. I haven’t done much to it since the merge. Tonight and this weekend we will be going through it to make sure it is iOS 9 ready. We have an app that will be sent to Apple as well that will confirm all is okay. 



---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by cohix** [comment]
Sounds good, I'll test on dev branch starting Monday.

**Comment by cohix** [comment]
@danieldahan I still get the lldb error on the development branch.

**Comment by danieldahan** [comment]
Can you copy and paste the error message?

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by cohix** [comment]
(lldb)

Thread 20: breakpoint 1.1

Nothing else is given.

**Comment by danieldahan** [comment]
So what I need your help in doing, is to give as much context to the issue, because I am not able to reproduce it. Any additional information would be great. Also, do a latest pull of dev. 

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by cohix** [comment]
Honestly I can't figure it out either. I've been trying to debug it all morning. The error is not consistently thrown, and although it causes the app to crash while connected to Xcode, I cannot seem to make the app crash when disconnected. Nothing other than the button itself is show in the scope, and everything inside the button looks fine.

**Comment by danieldahan** [comment]
Can you post the code for adding the button and such?

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
@cohix any luck with this?

**Comment by cohix** [comment]
No, none. You can close the issue if you'd like. I submitted an update 
using the
development branch. As far as I can tell the issue only happens when 
conmected
to Xcode so we'll see if it gets approved.

**Comment by danieldahan** [comment]
Thanks :) Keep us posted. We are submitting an app on Sunday with MaterialKit and will see if any issues arise.
